name: File checks
run-name: ${{ github.actor }} is trying to add a new file

on:
  pull_request:
    paths:
      - 'yml/*.yml'
      - '.src/config.json'

jobs:
  check-file-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: yaml-files

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Python script
        run: pip3 install -r yaml-files/.src/requirements.txt
      
      - name: Make "data" dir to prevent createDB from complaining
        run: mkdir "data"

      - name: Create Database
        run: python3 yaml-files/.src/createDB.py yaml-files/

  enable-auto-merge:
    needs: check-file-structure  
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["automerge"]
            })
      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()
