name: File checks
run-name: ${{ github.actor }} is trying to add a new file

on:
  # workflow_dispatch:
  #   inputs:
  #     pr_number:
  #       description: 'Pull request number'
  #       required: true
  pull_request:
    types: [opened, synchronize, reopened]
    # paths:
    #   - 'yml/*.yml'

permissions:
  contents: write
  pull-requests: write  # Needed to enable auto-merge
  issues: write         # Needed to add labels
  
concurrency:
  group: yaml-processing-pipeline
  cancel-in-progress: false
  
jobs:
  check-file-structure:
    runs-on: ubuntu-latest
    outputs:
      force_push_needed: ${{ steps.rebase.outputs.force_push_needed }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: yaml-files
          fetch-depth: 0  # Fetch full history
          submodules: recursive  # In case you have submodules

      - name: Merge main into PR branch
        id: rebase
        run: |
          cd yaml-files
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if this PR is based on the current main branch
          git fetch origin main
          BASE_SHA=$(git merge-base HEAD origin/main)
          MAIN_SHA=$(git rev-parse origin/main)
          
          if [ "$BASE_SHA" = "$MAIN_SHA" ]; then
            echo "PR is already based on current main branch, no rebase needed."
            echo "force_push_needed=false" >> $GITHUB_ENV
            echo "force_push_needed=false" >> $GITHUB_OUTPUT
          else
            echo "PR is based on an older version of main, rebasing..."
            if git rebase origin/main; then
              echo "Rebase successful, force pushing..."
              git commit --allow-empty -m "Trigger workflow run"
              git push --force-with-lease origin HEAD:${{ github.head_ref }}
              echo "force_push_needed=true" >> $GITHUB_ENV
              echo "force_push_needed=true" >> $GITHUB_OUTPUT
            else
              echo "Rebase failed, aborting."
              git rebase --abort
              exit 1
            fi
          fi

      - name: Skip if force push happened
        if: env.force_push_needed == 'true'
        run: |
          echo "Force push happened, exiting early."
          exit 0

      - name: Setup Python
        if: env.force_push_needed == 'false'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Python script
        if: env.force_push_needed == 'false'
        run: pip3 install -r yaml-files/.src/requirements.txt
      
      - name: Make "data" dir to prevent createDB from complaining
        if: env.force_push_needed == 'false'
        run: mkdir "data"

      - name: Create Database
        if: env.force_push_needed == 'false'
        run: python3 yaml-files/.src/createDB.py yaml-files/

  enable-auto-merge:
    needs: check-file-structure
    runs-on: ubuntu-latest
    if: needs.check-file-structure.outputs.force_push_needed == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get PR Number
        id: get_pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Get PR Branch Name
        id: get_branch
        run: echo "BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add automerge label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(process.env.PR_NUMBER, 10),
              labels: ["automerge"]
            });

      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash $PR_NUMBER
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for PR to close
        run: |
          for i in {1..30}; do
            state=$(gh pr view $PR_NUMBER --json state -q .state)
            echo "Current PR state: $state"
            if [ "$state" = "MERGED" ] || [ "$state" = "CLOSED" ]; then
              echo "PR is merged or closed. Continuing..."
              exit 0
            fi
            echo "PR still open. Sleeping for 10 seconds..."
            sleep 10
          done
          echo "Timed out waiting for PR to close."
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
